version: "3"
services:
  nginx:
    build: ./build/nginx
    container_name: dnginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
      - net-php

  php:
    build: ./build/php/
    container_name: dphp
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php/:/var/log/php7/:rw
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    build: ./build/mysql
    container_name: dmysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql/:/var/lib/mysql/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    build: ./build/redis
    container_name: dredis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - net-redis
    volumes:
    - ./conf/redis/redis.conf:/etc/redis/redis.conf:ro
    - ./log/redis/:/var/log/redis/:rw
    - ./data/redis/:/data/:rw

networks:
  net-php:
  net-mysql:
  net-redis:
