FROM php:7-fpm-alpine

# change source
RUN cp /etc/apk/repositories /etc/apk/repositories.bak \
	&& echo "http://mirrors.aliyun.com/alpine/v3.7/main/" > /etc/apk/repositories \
	&& echo "http://mirrors.aliyun.com/alpine/v3.7/community/" >> /etc/apk/repositories \
    && apk add -U --no-cache --virtual .build-deps \
        # gd
        libpng-dev \
        libjpeg-turbo-dev \
        libwebp-dev \
        libxpm-dev \
        # bz2
        bzip2-dev \
        # soap
        libxml2-dev \
        # enchant
        enchant-dev \
        # openssl replace openssl-dev/libressl-dev in 3.7
        #libressl2.6-libcrypto \
        # gmp
        gmp-dev \
        # imap
        imap-dev \
        icu-dev \
        # ldap
        openldap-dev \
        # odbc
        #unixodbc \
        #unixodbc-dev \
        # snmp
        net-snmp-dev \
        freetype-dev \
        ncurses-dev \
        # mcrypt
        libmcrypt-dev \
        # xsl
        libxslt-dev \
        libevent-dev \
        flex-dev \
        # pdo_dblib
        freetds-dev \
        # recode
        #recode-dev \
        # snmp
        net-snmp-dev \
        # pspell
        #aspell-dev \
        # tidy
        tidyhtml-dev \
        # install everything needed  “##” means offical alpine image already include \
        && docker-php-ext-install \
        #########################################
        ## offical alpine image already include
        ##ctype \
        ##curl \
        ##dom \
        ##fileinfo \
        ##filter \
        ##ftp \
        ##hash \
        ##iconv \
        ##json \
        ##mbstring \
        ##pdo \
        ##pdo_sqlite \
        ##phar \
        ##posix \
        ##reflection \
        ##session \
        ##readline \
        ##sodium \
        ##spl \
        ##standard \
        ##tokenizer \
        ##xml \
        ##xmlreader \
        ##simplexml \
        ##xmlwriter \
        #########################################
        bcmath \
        bz2 \
        calendar \
        dba \
        enchant \
        exif \
        gd \
        gettext \
        gmp \
        imap \
        intl \
        ldap \
        mysqli \
        opcache \
        pcntl \
        pdo_dblib \
        pdo_mysql \
        shmop \
        snmp \
        soap \
        sockets \
        sysvmsg \
        sysvsem \
        sysvshm \
        wddx \
        xmlrpc \
        xsl \
        zend_test \
        zip \
        ##################################
        # need to install tidy
        tidy
        ##################################
        #################################################
        # need to install interbase and specify the path
        #interbase \
        #pdo_firebird \
        #################################################
        ##############################################
        # need to install oracle and specify the path
        #oci8 \
        #pdo_oci \
        ##############################################
        ####################################################
        # need to install DB2 unixODBC and specify the path
        #odbc \
        #pdo_odbc \
        ####################################################
        ##################################################
        # need to install postgresql and specify the path
        #pdo_pgsql \
        #pgsql \
        ##################################################
        ##############################################
        # need to install aspell and specify the path
        #pspell \
        ##############################################
        ####################################
        # need to install recode recode-dev
        #recode \
        ####################################
        && apk del .build-deps

# install redis ext
RUN apk add --no-cache --virtual .build-deps gcc g++ autoconf make \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del .build-deps \
    && pecl update-channels \
    && rm -rf /tmp/pear ~/.pearrc

# install memcached ext
RUN apk add --no-cache libmemcached-dev zlib-dev \
    && apk add --no-cache --virtual .build-deps gcc g++ autoconf make  \
	&& pecl install memcached \
    && docker-php-ext-enable memcached \
    && apk del .build-deps \
    && pecl update-channels \
    && rm -rf /tmp/pear ~/.pearrc

# install mongodb ext
RUN apk add --no-cache  --virtual .build-deps gcc g++ autoconf make \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && apk del .build-deps \
    && pecl update-channels \
    && rm -rf /tmp/pear ~/.pearrc

# install swoole ext
RUN apk add --no-cache  --virtual .build-deps gcc g++ autoconf make \
    && pecl install swoole \
    && docker-php-ext-enable mongodb \
    && apk del .build-deps \
    && pecl update-channels \
    && rm -rf /tmp/pear ~/.pearrc

# install Composer
RUN /usr/local/bin/php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /bin/composer \
    && composer config -g repo.packagist composer https://packagist.phpcomposer.com
